import Head from "next/head";
import Header from "../components/Header";
import SideBar from "../components/SideBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FaceBook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex bg-gray-100">
        {/* Left Sidebar */}
        <SideBar />
        {/* Feed (Create Post and Posts) */}
        {/* Right Sidebar */}
      </main>
    </div>
  );
}
